### PR TITLE
fix: Meta Tags and Favicons 

### LINKED ISSUE #10: Add meta tags
Add all meta tags and change the react app name along with the favicon.

Resources:

- https://metatags.io/ - For generating meta tags.
- Change react app name to "Design and Code"
- Favicon: DC Logo 

If you need anything ping me on discord! https://discord.gg/druweDMn3s

### PR DESCRIPTION
**Pull request by Alkaison**
**Please check if the PR fulfills these requirements:**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] The code related to the changes has been properly commented

**What kind of change does this PR introduce?** _(select / add custom)_

- feature: adds meta tags and new favicons 

**What is the current behavior?** _(link the issue here)_

- Fixes #10 
- New Meta Tags 
- New favicons with manifest 

**What is the new behavior?**

- Meta tags will help in increasing the SEO of the website.

### CODE REVIEW

**Comment by Alkaison** [comment]
- Added Meta Tags 
- Added new Favicons for different devices with manifest

Here's the list of meta tags I have implemented:

```HTML
          <meta name="theme-color" content={theme.palette.primary.main} />
          <link rel="shortcut icon" href="favicon.ico" />
          <meta name="emotion-insertion-point" content="" />
          {/* <!-- Primary Meta Tags --> */}
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <meta name="description" content="Design and Code a global community where anyone can learn and network with fellow developers and designers." />
          {/* <!-- Facebook --> */}
          <meta property="og:type" content="website" />
          <meta property="og:url" content="https://www.designandcode.us/" />
          <meta property="og:title" content="Home | Design and Code" />
          <meta property="og:description" content="Design and Code a global community where anyone can learn and network with fellow developers and designers." />
          <meta property="og:image" content="static\branding-logos\branding-transparent-logo.svg" />
          {/* <!-- Twitter --> */}
          <meta property="twitter:card" content="summary_large_image" />
          <meta property="twitter:url" content="https://www.designandcode.us/" />
          <meta property="twitter:title" content="Home | Design and Code" />
          <meta property="twitter:description" content="Design and Code a global community where anyone can learn and network with fellow developers and designers." />
          <meta property="twitter:image" content="static\branding-logos\branding-transparent-logo.svg" />
          {/* <!-- SEO Tags --> */}
          <meta name="language" content="EN" />
          <meta property="og:locale" content="en" />
          <meta property="og:type" content="website" />
          <meta property="og:site_name" content="Home | Design and Code" />
          <meta name="url" content="https://www.designandcode.us/" />
          <meta name="coverage" content="Worldwide" />
          <meta name="distribution" content="Global" />
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <meta content="yes" name="apple-touch-fullscreen" />
          <meta name="copyright" content="Home | Design and Code" />
          {/* <!--
              Notice the use of %PUBLIC_URL% in the tags above.
              It will be replaced with the URL of the `public` folder during the build.
              Only files inside the `public` folder can be referenced from the HTML.
              Unlike "/favicon.ico" or "favicon.ico", "%PUBLIC_URL%/favicon.ico" will
              work correctly both with client-side routing and a non-root public URL.
              Learn how to configure a non-root public URL by running `npm run build`.
          -->
          <!-- Favicons for different devices --> */}
          <link rel="apple-touch-icon" sizes="180x180" href="favicon/apple-touch-icon.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="favicon/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="favicon/favicon-16x16.png" />
          {/* <!--
              site.webmanifest provides metadata used when your web app is installed on a
              user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
          --> */}
          <link rel="manifest" href="favicon/site.webmanifest" />
```

File: src/pages/_document.tsx [hunk 1]
```diff
@@ -10,6 +10,50 @@ export default class MyDocument extends Document {
           <meta name="theme-color" content={theme.palette.primary.main} />
           <link rel="shortcut icon" href="favicon.ico" />
```
Comment (Panquesito7) [inline src/pages/_document.tsx:11]: You should probably update the link to the favicon here.

File: src/pages/_document.tsx [hunk 2]
```diff
@@ -10,6 +10,50 @@ export default class MyDocument extends Document {
...
           <meta name="emotion-insertion-point" content="" />
+          {/* <!-- Primary Meta Tags --> */}
+          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
+          <meta name="description" content="Design and Code a global community where anyone can learn and network with fellow developers and designers." />
+          {/* <!-- Facebook --> */}
+          <meta property="og:type" content="website" />
+          <meta property="og:url" content="https://www.designandcode.us/" />
+          <meta property="og:title" content="Home | Design and Code" />
```
Comment (Panquesito7) [inline src/pages/_document.tsx:19]: Shouldn't `Home` be the name of the current page instead?

File: public/favicon/site.webmanifest [hunk 3]
```diff
@@ -0,0 +1 @@
+{"name":"Home | Design and Code","short_name":"DC","icons":[{"src":"/android-chrome-192x192.png","sizes":"192x192","type":"image/png"},{"src":"/android-chrome-512x512.png","sizes":"512x512","type":"image/png"}],"theme_color":"#ffffff","background_color":"#ffffff","display":"standalone"}
```
Comment (Panquesito7) [inline public/favicon/site.webmanifest:1]: Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
{"name":"Home | Design and Code","short_name":"DC","icons":[{"src":"/android-chrome-192x192.png","sizes":"192x192","type":"image/png"},{"src":"/android-chrome-512x512.png","sizes":"512x512","type":"image/png"}],"theme_color":"#ffffff","background_color":"#ffffff","display":"standalone"}

```

**Review by Panquesito7 — CHANGES_REQUESTED** [review]

File: public/favicon/site.webmanifest (hunk 3 above)
Comment (Alkaison) [reply public/favicon/site.webmanifest]: Done ✅

File: src/pages/_document.tsx (hunk 2 above)
Comment (Alkaison) [reply src/pages/_document.tsx]: Removed it. Done ✅

File: src/pages/_document.tsx (hunk 1 above)
Comment (Alkaison) [reply src/pages/_document.tsx]: Updated it to the favicon/favicon.ico file path

File: src/pages/_document.tsx [hunk 4]
```diff
@@ -8,8 +8,44 @@ export default class MyDocument extends Document {
...
           <meta name="theme-color" content={theme.palette.primary.main} />
-          <link rel="shortcut icon" href="favicon.ico" />
           <meta name="emotion-insertion-point" content="" />
+          {/* <!-- Primary Meta Tags --> */}
+          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
+          <meta name="description" content="Design and Code a global community where anyone can learn and network with fellow developers and designers." />
+          {/* <!-- Facebook --> */}
+          <meta property="og:type" content="website" />
+          <meta property="og:url" content="https://www.designandcode.us/" />
+          <meta property="og:title" content="Design and Code" />
```
Comment (Panquesito7) [inline src/pages/_document.tsx:18]: Shouldn't we add the name of the page the user is on?
For example: if it's the documentation page, use `Documentation | Design and Code`.

Also, I'm not 100% sure we want to add meta tags to all websites. 🤔 
CC: @Design-and-Code/project-maintainers.

Comment (Alkaison) [reply src/pages/_document.tsx:18]: - Content of this file **__documents.tsx_** will be applied to all webpages. 

- So we don't need to add the names of the pages like home, contact, documentation to meta tag because every page contain their own title tag.

- meta tags helps in ranking our website on top in search results and improves indexing stats of the contents.

- you should definitely add them!

Comment (Panquesito7) [reply src/pages/_document.tsx:18]: Cool, thanks. :)
However, isn't there a way of obtaining the title of the current webpage the user is visiting? There should be a way to do so, as it's on the `_document.tsx` file, and then we can properly apply the title of each page.

Comment (Alkaison) [reply src/pages/_document.tsx:18]: - I guess there should be a way to do that. I will try to implement it today.

- other than that is the **PR** ready for merge? @Panquesito7

**Comment by Alkaison** [comment]
- I had try hard to add that feature of title attribute content using auto detect but its causing errors.
- I request you to merge this **`PR`** for **`meta tags improvement`**.
- I will create a new PR later for that feature and will work on it.

**Thanks!**

File: src/pages/_document.tsx [hunk 5]
```diff
@@ -64,4 +100,4 @@ MyDocument.getInitialProps = async (ctx) => {
     ...initialProps,
     emotionStyleTags,
   };
-};
+};
```
Comment (Panquesito7) [inline src/pages/_document.tsx:103]:
```suggestion
};

```

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🚀

**Comment by Alkaison** [comment]
- 5 days passed and no response from review team. 😑
- Will this PR ever be merged ?

**Comment by Panquesito7** [comment]
> * 5 days passed and no response from review team. 😑
> * Will this PR ever be merged ?

1. Please be patient. The review team is busy with much other stuff.
2. It will once it is approved by the other maintainers.

**Comment by Greeshma2903** [comment]
Sorry for the delays, merged 🙌🏽 Thank you for contributing!

**Comment by Alkaison** [comment]
- Thanks a lot!
